import Head from "next/head";
import Image from "next/image";
import Contact from "../components/Contact";
import Divider from "../components/Divider";
import Experiences from "../components/Experiences";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Projects from "../components/Projects";
import styles from "../styles/Home.module.css";
import { useSelector } from "react-redux";

export default function Home() {
  const dark = useSelector((state) => state.dark);
  return (
    <>
      <div className={dark ? styles.container : styles.containerLight}>
        <Head>
          <title>Ehtesham&apos;s Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.png" />
        </Head>
        <div className={styles.contents}>
          <Navbar />
          <Hero />
          <Experiences />
          <Divider />
          <Projects />
          <Divider />
          <Contact />
        </div>
      </div>
    </>
  );
}
